[project]
name = "pledgeboard"
description = "Community pledge tracker"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.pledgeboard]
path = "contracts/pledgeboard.clar"

[repl.analysis]
passes = ["check_checker"]
